language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install: "pip install requests==2.2 $DJANGO_VERSION"
env:
  global:
    - PYTHONWARNINGS=all DJANGO_SETTINGS_MODULE=tests.django_settings
  matrix:
    - DJANGO_VERSION='Django>=1.5,<1.6'
    - DJANGO_VERSION='Django>=1.6,<1.7'
    - DJANGO_VERSION='https://www.djangoproject.com/download/1.7c2/tarball/#egg=Django'
    #- DJANGO_VERSION='>=1.7,<1.8'
matrix:
  include:
    - python: 2.7
      env: DJANGO_VERSION='Django>=1.4,<1.5'
    - python: "pypy"
      env: DJANGO_VERSION='Django>=1.4,<1.5'
script: python -m unittest discover
